"""Promptfoo export adapter — the first export target per the design.

Renders the Blueprint IR's behavioral tests into a declarative promptfoo config.
The ``providers`` entry is a placeholder for the *agent under test*; running the
suite (Phase 5 / downstream) requires pointing it at the real agent.
"""

from __future__ import annotations

import yaml

from qa_architect.ir import (
    AssertionKind,
    BehavioralTest,
    EvaluationBlueprint,
)

# Placeholder provider — replace with the agent under test before `promptfoo eval`.
_PLACEHOLDER_PROVIDER = "openai:chat:gpt-4o-mini"


def _assertion_to_promptfoo(test: BehavioralTest) -> dict:
    a = test.assertion
    if a.kind is AssertionKind.LLM_RUBRIC:
        return {"type": "llm-rubric", "value": a.value}
    if a.kind is AssertionKind.REGEX:
        return {"type": "regex", "value": a.value}
    if a.kind is AssertionKind.EQUALS:
        return {"type": "equals", "value": a.value}
    if a.kind is AssertionKind.CONTAINS:
        return {"type": "contains", "value": a.value}
    # metric_ref and anything else fall back to a rubric judgement.
    return {"type": "llm-rubric", "value": a.value}


def to_promptfoo_config(blueprint: EvaluationBlueprint) -> dict:
    """Build a promptfoo config dict from the blueprint's behavioral tests."""
    tests = []
    for t in blueprint.tests:
        tests.append(
            {
                "description": f"{t.id} | {','.join(t.requirement_ids)} | {t.category.value}",
                "vars": {"input": t.input},
                "assert": [_assertion_to_promptfoo(t)],
                "metadata": {
                    "test_id": t.id,
                    "requirement_ids": t.requirement_ids,
                    "category": t.category.value,
                    "expected_behavior": t.expected_behavior,
                },
            }
        )

    return {
        "description": (
            f"AI QA Architect blueprint {blueprint.generation_run_id} "
            f"({len(tests)} behavioral tests for {blueprint.doc_metadata.source_name})"
        ),
        # Replace with the agent under test, e.g. file://./agent.py or a provider id.
        "providers": [_PLACEHOLDER_PROVIDER],
        "prompts": ["{{input}}"],
        "tests": tests,
    }


def to_promptfoo_yaml(blueprint: EvaluationBlueprint) -> str:
    config = to_promptfoo_config(blueprint)
    header = (
        "# Generated by AI QA Architect. Set `providers` to the agent under test\n"
        "# before running `promptfoo eval`.\n"
    )
    return header + yaml.safe_dump(config, sort_keys=False, allow_unicode=True)
